import type { NextConfig } from "next";
// 301s for blog URLs that were cut mid-word or left a dangling hyphen by the old
// slug generator. Generated by scripts/fix-truncated-slugs.mjs; the posts were
// renamed, so without these the old indexed URLs would 404.
import slugRedirects from "./data/slug-redirects.json";

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "ksa.ee",
        pathname: "/wp-content/uploads/**",
      },
      {
        protocol: "https",
        hostname: "raw.githubusercontent.com",
        pathname: "/antshaavel22/ksa-blog/**",
      },
    ],
  },
  async redirects() {
    return [
      // Language path → query param (blog uses ?keel=xx, not /xx routes).
      // Fixes 404 on /ru, /en, /et that Googlebot + paid ads were hitting.
      { source: "/ru", destination: "/?keel=ru", permanent: true },
      { source: "/ru/", destination: "/?keel=ru", permanent: true },
      { source: "/en", destination: "/?keel=en", permanent: true },
      { source: "/en/", destination: "/?keel=en", permanent: true },
      { source: "/et", destination: "/", permanent: true },
      { source: "/et/", destination: "/", permanent: true },
      {
        source: "/blogi",
        destination: "/",
        permanent: false,
      },
      {
        source: "/blogi/:path*",
        destination: "/:path*",
        permanent: false,
      },
      {
        source: "/flow3-laserkorrektsiooni-lahendus-frustreeritud-prillikandjaile",
        destination: "/miks-59-protsenti-prillikandjaid-on-frustreeritud-2",
        permanent: true,
      },
      {
        source: "/flow3-laserkorrektsiooni-eelis-100-paeeva-aastas-tagasi",
        destination: "/100-paeva-sinu-elust-prillide-varjatud-ajamaks-2",
        permanent: true,
      },
      // Common RSS discovery paths → the real feed route.
      { source: "/feed", destination: "/rss.xml", permanent: true },
      { source: "/feed/", destination: "/rss.xml", permanent: true },
      { source: "/rss", destination: "/rss.xml", permanent: true },
      ...slugRedirects,
    ];
  },
  // Security headers for the mounted blog zone.
  async headers() {
    return [
      {
        source: "/(.*)",
        headers: [
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "X-Frame-Options", value: "DENY" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
        ],
      },
    ];
  },
};

export default nextConfig;
